// Governance Layer - Policy Check Agent
// Enforces all governance rules before response is sent to user

export function runPolicyChecks(analysisData, userConfirmed = false) {
  const startTime = Date.now();
  const checks = {};
  let allPassed = true;
  
  // Check 1: Confidence Sufficient
  checks.confidence_sufficient = analysisData.confidence >= 55 || analysisData.risk_level === 'UNKNOWN';
  if (!checks.confidence_sufficient && analysisData.risk_level !== 'UNKNOWN') {
    // Force to UNKNOWN if confidence is low
    analysisData.risk_level = 'UNKNOWN';
  }
  
  // Check 2: No Auto-Submission (always true - system never auto-submits)
  checks.no_auto_submission = true;
  
  // Check 3: No Data Retained (always true - session-only processing)
  checks.no_data_retained = true;
  
  // Check 4: Human in Loop (for report generation)
  checks.human_in_loop = true; // Will be checked separately during report generation
  
  // Check 5: Scope Check (language and topic)
  checks.scope_check = true; // Already validated in InputNormaliser
  
  // Determine if all checks passed
  allPassed = Object.values(checks).every(check => check === true);
  
  return {
    passed: allPassed,
    checks,
    time_ms: Date.now() - startTime,
    trace: {
      step: 5,
      agent: 'PolicyCheck',
      model: 'Governance Layer',
      action: 'Validate confidence, data privacy, human-in-loop rules',
      result: allPassed ? '✓ All governance checks passed' : '⚠ Some checks failed',
      time_ms: Date.now() - startTime,
      policy_passed: allPassed,
      checks
    }
  };
}

export function validateReportGeneration(userConfirmed) {
  // RULE 1 & 4: Human in the Loop - ABSOLUTE
  if (!userConfirmed) {
    return {
      allowed: false,
      error: 'User confirmation required before generating police report.',
      code: 'CONFIRMATION_REQUIRED'
    };
  }
  
  return {
    allowed: true
  };
}

export function getLegalNotice(language = 'en') {
  const notices = {
    en: {
      heading: '⚠️ LEGAL NOTICE — Read Before Proceeding',
      text: 'Filing a false or frivolous complaint is a criminal offence punishable under IPC Section 182 and IT Act Section 66. This report has been auto-generated by BobSec AI based on the message you provided. You must review it carefully for accuracy before submitting. BobSec does not submit this report on your behalf. Submission is entirely your responsibility.'
    },
    hi: {
      heading: '⚠️ कानूनी सूचना — आगे बढ़ने से पहले पढ़ें',
      text: 'झूठी या गलत शिकायत दर्ज करना IPC धारा 182 और IT अधिनियम धारा 66 के तहत दंडनीय अपराध है। यह रिपोर्ट BobSec AI द्वारा आपके दिए गए मैसेज के आधार पर बनाई गई है। जमा करने से पहले इसे ध्यान से पढ़ें। BobSec यह रिपोर्ट आपकी तरफ से जमा नहीं करता।'
    }
  };
  
  return notices[language] || notices.en;
}

// Distressed user protocol
export function getDistressedUserMessage(language = 'en') {
  const messages = {
    en: "I understand this is stressful. Let's handle this together, step by step.",
    hi: "मैं समझता/समझती हूँ यह परेशान करने वाला है। चलिए मिलकर इसे handle करते हैं।"
  };
  
  return messages[language] || messages.en;
}

// Next steps suggestions based on scenario
export function suggestNextSteps(category, alreadyClicked = false, alreadyPaid = false) {
  if (alreadyPaid) {
    return [
      "Call your bank immediately (HDFC: 1800-258-3838 / SBI: 1800-425-3800 / general: your bank's helpline). Tell them you were scammed. Ask for a transaction freeze.",
      "File a complaint on cybercrime.gov.in within the next hour — speed of reporting increases recovery chances.",
      "Call National Cyber Crime Helpline: 1930 (24/7, free). They can coordinate with banks.",
      "Do not share any more information with anyone who contacts you about this — scammers often call again pretending to help.",
      "Tell a trusted family member or friend. You should not handle this alone."
    ];
  }
  
  if (alreadyClicked) {
    return [
      "Change your bank/UPI password right now from a different device or browser.",
      "If you entered an OTP, call your bank immediately to freeze your account.",
      "Do not enter any OTP or PIN that arrives now — ignore it and do not share it with anyone.",
      "Run a security check on your device (Settings → Security → check for unknown apps).",
      "Call 1930 to report."
    ];
  }
  
  // Preventive action
  return [
    "Block this number/sender immediately.",
    "Do not reply, click, or engage in any way — even to say 'wrong number.'",
    "Report the number on cybercrime.gov.in or call 1930.",
    "Share this scam pattern with family and friends so they are not targeted next."
  ];
}

// Made with Bob
