// ReportDraftAgent - Creates NCRP-compliant complaint drafts
// Handles both pre_incident (prevention) and post_incident (victim assistance) modes

const NCRP_INCIDENT_TYPE = {
  FINANCIAL_FRAUD: 'Online Financial Fraud',
  PHISHING: 'Phishing / Credential Theft',
  JOB_SCAM: 'Online Job Fraud',
  LOTTERY_SCAM: 'Lottery / Prize Fraud',
  IMPERSONATION: 'Impersonation of Government/Bank',
  INVESTMENT_SCAM: 'Investment / Ponzi Fraud',
  UNKNOWN: 'Cybercrime (Unclassified)'
}

// Generate pre-incident report (prevention mode)
function generatePreIncidentReport(analysis, enrichedEntities) {
  const phones = enrichedEntities.phone_numbers?.map(p => p.value).join(', ') || 'Unknown sender'
  const urls = enrichedEntities.urls?.map(u => u.value).join(', ') || 'None'
  const upis = enrichedEntities.upi_ids?.map(u => u.value).join(', ') || 'None'
  const org = enrichedEntities.impersonated_org || 'Unknown organisation'
  const flags = analysis.red_flags?.join('; ') || 'See evidence package'
  const firstUrl = enrichedEntities.urls?.[0]
  const firstPhone = enrichedEntities.phone_numbers?.[0]
  const incidentType = NCRP_INCIDENT_TYPE[analysis.category] || 'Cybercrime'

  const urlPara = firstUrl
    ? `The message contained a suspicious link (${firstUrl.value}) which BobSec identified as ${firstUrl.verdict.toLowerCase()} - registered ${firstUrl.domain_age_days} days ago and flagged by ${firstUrl.feed_hits} threat intelligence sources.`
    : ''

  const phonePara = firstPhone
    ? `The phone number (${firstPhone.value}) has been reported ${firstPhone.report_count} times by the community for similar ${firstPhone.scam_type?.replace(/_/g, ' ').toLowerCase() || 'fraud'} activity.`
    : ''

  return `CYBERCRIME COMPLAINT — NCRP FORMAT
${'═'.repeat(55)}

SECTION A — INCIDENT DETAILS
Incident Type    : ${incidentType}
Date & Time      : ${analysis.timestamp_ist}
Platform         : WhatsApp / SMS
Status           : PREVENTED (No financial loss)

SECTION B — COMPLAINT DESCRIPTION
On ${analysis.timestamp_ist}, I received a suspicious message from ${phones} that attempted to impersonate ${org}. The message claimed ${enrichedEntities.urgency_phrases?.[0] || 'urgent action was required'} and directed me to take action that would have compromised my personal and financial information.

${urlPara}

${phonePara}

I did NOT respond to this message, click any links, or share any information. I am filing this complaint proactively to assist in investigation and to warn others who may receive similar messages.

Red flags identified by BobSec AI: ${flags}.

I request appropriate action against the fraudulent ${firstPhone ? 'number' : ''}${firstUrl ? ' and domain' : ''} to prevent others from falling victim.

SECTION C — EVIDENCE SUMMARY
Evidence Type    : AI-Generated Threat Analysis (BobSec / IBM Bob)
Analysis ID      : ${analysis.analysis_id}
Timestamp        : ${analysis.timestamp_ist}
Risk Score       : ${analysis.risk_score} / 100 (${analysis.risk_level})
Confidence Level : ${analysis.confidence}%
Category         : ${incidentType}
Entities Found   : Phones: ${phones} | URLs: ${urls} | UPI: ${upis}
Intel Feed Hits  : ${firstUrl ? firstUrl.feed_hits + ' CTI feed matches' : '0'}
Model Used       : IBM Granite via watsonx.ai (IBM Bob Orchestration)

${'═'.repeat(55)}
This report was auto-generated by BobSec AI. The complainant has reviewed it and confirms its accuracy before submission. BobSec does not submit this report on behalf of the user.`
}

// Generate post-incident report (victim assistance mode)
function generatePostIncidentReport(analysis, enrichedEntities, victimNarrative) {
  const phones = enrichedEntities.phone_numbers?.map(p => p.value).join(', ') || 'Unknown sender'
  const urls = enrichedEntities.urls?.map(u => u.value).join(', ') || 'None'
  const upis = enrichedEntities.upi_ids?.map(u => u.value).join(', ') || 'None'
  const org = enrichedEntities.impersonated_org || 'Unknown organisation'
  const incidentType = NCRP_INCIDENT_TYPE[analysis.category] || 'Cybercrime'
  
  // Extract amounts from narrative or entities
  const amounts = enrichedEntities.amounts?.join(', ') || 'Amount to be specified'
  
  // Build timeline from narrative
  const timeline = buildTimeline(victimNarrative, enrichedEntities)

  return `CYBERCRIME COMPLAINT — NCRP FORMAT (POST-INCIDENT)
${'═'.repeat(55)}

SECTION A — INCIDENT DETAILS
Incident Type    : ${incidentType}
Date & Time      : ${analysis.timestamp_ist}
Platform         : WhatsApp / SMS
Status           : VICTIM - Financial loss occurred
Financial Loss   : ${amounts}

SECTION B — DETAILED INCIDENT NARRATIVE

${victimNarrative.description || 'I was contacted by a fraudster who impersonated ' + org + ' and convinced me to share sensitive information / transfer money.'}

TIMELINE OF EVENTS:
${timeline}

FRAUDULENT ENTITIES INVOLVED:
- Phone Number(s): ${phones}
- Website(s): ${urls}
- UPI ID(s): ${upis}
- Impersonated Organisation: ${org}

ACTIONS TAKEN BY VICTIM:
${victimNarrative.actions_taken || '- Shared OTP / credentials\n- Transferred money\n- Clicked on malicious link'}

IMMEDIATE STEPS TAKEN AFTER REALIZING FRAUD:
${victimNarrative.steps_after || '- Contacted bank to freeze account\n- Changed passwords\n- Filed this complaint'}

SECTION C — EVIDENCE & ANALYSIS
BobSec AI Analysis ID : ${analysis.analysis_id}
Risk Assessment       : ${analysis.risk_score}/100 (${analysis.risk_level})
Scam Category         : ${incidentType}
Confidence Level      : ${analysis.confidence}%

THREAT INTELLIGENCE:
${enrichedEntities.phone_numbers?.map(p => 
  `- Phone ${p.value}: ${p.report_count} prior reports for ${p.scam_type || 'fraud'}`
).join('\n') || '- No prior reports found'}
${enrichedEntities.urls?.map(u => 
  `- Domain ${u.value}: ${u.verdict} (${u.domain_age_days} days old, ${u.feed_hits} threat feeds)`
).join('\n') || ''}

SECTION D — RELIEF SOUGHT
1. Immediate action to freeze/block the fraudulent phone number(s) and UPI ID(s)
2. Investigation and prosecution of the perpetrators
3. Assistance in recovering the lost amount
4. Prevention of similar fraud against other citizens

${'═'.repeat(55)}
This report was generated with assistance from BobSec AI (IBM Bob). All information provided is accurate to the best of my knowledge. I am willing to cooperate fully with the investigation.

Complainant's Declaration: I hereby declare that the above information is true and correct. I understand that filing a false complaint is a punishable offence.`
}

// Build timeline from victim narrative
function buildTimeline(narrative, entities) {
  if (narrative.timeline && Array.isArray(narrative.timeline)) {
    return narrative.timeline.map((event, i) => 
      `${i + 1}. ${event.time || 'Time unknown'}: ${event.description}`
    ).join('\n')
  }

  // Generate basic timeline from entities
  const events = []
  
  if (entities.dates && entities.dates.length > 0) {
    events.push(`1. ${entities.dates[0]}: Initial contact received`)
  } else {
    events.push(`1. Date/time unknown: Initial contact received`)
  }
  
  events.push(`2. Shortly after: Fraudster gained trust through impersonation`)
  events.push(`3. Subsequently: Victim shared sensitive information / made payment`)
  events.push(`4. Later: Victim realized it was fraud`)
  events.push(`5. Immediately: Victim took preventive action and filed this complaint`)
  
  return events.join('\n')
}

// Main ReportDraftAgent function
function generateReport(analysis, enrichedEntities, mode = 'pre_incident', victimNarrative = null) {
  const startTime = Date.now()

  let report
  if (mode === 'post_incident' && victimNarrative) {
    report = generatePostIncidentReport(analysis, enrichedEntities, victimNarrative)
  } else {
    report = generatePreIncidentReport(analysis, enrichedEntities)
  }

  return {
    report_text: report,
    mode: mode,
    incident_type: NCRP_INCIDENT_TYPE[analysis.category] || 'Cybercrime',
    processing_time_ms: Date.now() - startTime
  }
}

module.exports = { generateReport, NCRP_INCIDENT_TYPE }

// Made with Bob
