import jsPDF from 'jspdf'

export function generateEvidencePDF(analysis) {
  const doc = new jsPDF()
  const margin = 20
  let y = 20

  const line = (text, indent = 0) => {
    const lines = doc.splitTextToSize(text, 170 - indent)
    doc.text(lines, margin + indent, y)
    y += lines.length * 7
  }

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  line('BOBSEC EVIDENCE CERTIFICATE')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  y += 4
  doc.setDrawColor(200)
  doc.line(margin, y, 190, y)
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  line('CASE IDENTIFICATION')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  line(`Analysis ID    : ${analysis.analysis_id}`)
  line(`Timestamp      : ${analysis.timestamp_ist}`)
  line(`Model          : IBM Granite via watsonx.ai (IBM Bob Orchestration)`)
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  line('THREAT ASSESSMENT')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  line(`Risk Score     : ${analysis.risk_score} / 100 (${analysis.risk_level})`)
  line(`Confidence     : ${analysis.confidence}%`)
  line(`Category       : ${analysis.category}`)
  if (analysis.sub_type) line(`Sub-type       : ${analysis.sub_type}`)
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  line('ENTITIES IDENTIFIED')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)

  if (analysis.entities.phone_numbers?.length > 0) {
    analysis.entities.phone_numbers.forEach(p => {
      line(`Phone   : ${p.value} — ${p.verdict}${p.report_count ? ` (${p.report_count} community reports)` : ''}`, 4)
    })
  }
  if (analysis.entities.urls?.length > 0) {
    analysis.entities.urls.forEach(u => {
      line(`URL     : ${u.value} — ${u.verdict}${u.domain_age_days ? ` (${u.domain_age_days} days old, ${u.feed_hits} CTI feeds)` : ''}`, 4)
    })
  }
  if (analysis.entities.upi_ids?.length > 0) {
    analysis.entities.upi_ids.forEach(u => {
      line(`UPI     : ${u.value} — ${u.verdict}${u.report_count ? ` (${u.report_count} reports)` : ''}`, 4)
    })
  }
  if (analysis.entities.impersonated_org) {
    line(`Org     : ${analysis.entities.impersonated_org} (impersonated)`, 4)
  }
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  line('RED FLAGS')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  analysis.red_flags.forEach(flag => line(`· ${flag}`, 4))
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  line('AGENT VERIFICATION CHAIN')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  if (analysis.trace) {
    analysis.trace.forEach(t => {
      line(`Step ${t.step}: ${t.agent} → ${t.result} (${t.time_ms}ms)`, 4)
    })
  }
  y += 4

  doc.setDrawColor(200)
  doc.line(margin, y, 190, y)
  y += 6
  doc.setFontSize(8)
  doc.setTextColor(100)
  line('This evidence package was generated by BobSec AI (IBM Bob / watsonx.ai).')
  line('It reflects AI analysis only and does not constitute legal or forensic proof.')
  line('Submitted for informational purposes to assist law enforcement investigation.')

  doc.save(`BobSec_Evidence_${analysis.analysis_id}.pdf`)
}

export function generateReportPDF(analysis, reportText) {
  const doc = new jsPDF()
  const margin = 20
  let y = 20

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('CYBERCRIME COMPLAINT — NCRP FORMAT', margin, y)
  y += 10

  doc.setDrawColor(0)
  doc.line(margin, y, 190, y)
  y += 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')

  const lines = reportText.split('\n')
  lines.forEach(rawLine => {
    if (y > 270) { doc.addPage(); y = 20 }
    const wrapped = doc.splitTextToSize(rawLine, 170)
    doc.text(wrapped, margin, y)
    y += wrapped.length * 6
  })

  doc.save(`BobSec_PoliceReport_${analysis.analysis_id}.pdf`)
}

// Made with Bob
