const NCRP_TYPE = {
  FINANCIAL_FRAUD: 'Online Financial Fraud',
  PHISHING: 'Phishing / Credential Theft',
  JOB_SCAM: 'Online Job Fraud',
  LOTTERY_SCAM: 'Lottery / Prize Fraud',
  IMPERSONATION: 'Impersonation of Government/Bank',
  INVESTMENT_SCAM: 'Investment / Ponzi Fraud',
  UNKNOWN: 'Cybercrime (Unclassified)'
}

export function buildNCRPReport(analysis) {
  const phones = analysis.entities.phone_numbers?.map(p => p.value).join(', ') || 'Unknown sender'
  const urls = analysis.entities.urls?.map(u => u.value).join(', ') || 'None'
  const upis = analysis.entities.upi_ids?.map(u => u.value).join(', ') || 'None'
  const org = analysis.entities.impersonated_org || 'Unknown organisation'
  const flags = analysis.red_flags?.join('; ') || 'See evidence package'
  const firstUrl = analysis.entities.urls?.[0]
  const firstPhone = analysis.entities.phone_numbers?.[0]
  const incidentType = NCRP_TYPE[analysis.category] || 'Cybercrime'

  const urlPara = firstUrl
    ? `The message contained a suspicious link (${firstUrl.value}) which BobSec identified as a phishing domain registered ${firstUrl.domain_age_days} days ago and flagged by ${firstUrl.feed_hits} threat intelligence sources.`
    : ''

  const phonePara = firstPhone
    ? `The phone number (${firstPhone.value}) has been reported ${firstPhone.report_count} times for similar ${firstPhone.scam_type?.replace(/_/g, ' ').toLowerCase() || 'fraud'} activity.`
    : ''

  return `CYBERCRIME COMPLAINT — NCRP FORMAT
${'═'.repeat(55)}

SECTION A — INCIDENT DETAILS
Incident Type    : ${incidentType}
Date & Time      : ${analysis.timestamp_ist}
Platform         : WhatsApp / SMS

SECTION B — COMPLAINT DESCRIPTION
On ${analysis.timestamp_ist}, I received a message from ${phones} that impersonated ${org}. The message claimed ${analysis.entities.urgency_phrases?.[0] || 'urgent action was required'} and directed me to take action that would have compromised my personal and financial information.

${urlPara}

${phonePara}

Red flags identified: ${flags}.

I am filing this complaint to assist in investigation and to warn others. I request appropriate action against the fraudulent ${firstPhone ? 'number' : ''}${firstUrl ? ' and domain' : ''}.

SECTION C — EVIDENCE SUMMARY
Evidence Type    : AI-Generated Threat Analysis (BobSec / IBM Bob)
Analysis ID      : ${analysis.analysis_id}
Timestamp        : ${analysis.timestamp_ist}
Risk Score       : ${analysis.risk_score} / 100 (${analysis.risk_level})
Confidence Level : ${analysis.confidence}%
Category         : ${incidentType}
Entities Found   : Phones: ${phones} | URLs: ${urls} | UPI: ${upis}
Intel Feed Hits  : ${firstUrl ? firstUrl.feed_hits + ' CTI feed matches' : '0'}
Model Used       : IBM Granite via watsonx.ai (IBM Bob Orchestration)

${'═'.repeat(55)}
This report was auto-generated by BobSec AI. The complainant has reviewed it and confirms its accuracy before submission. BobSec does not submit this report on behalf of the user.`
}

// Made with Bob
