import { useState } from 'react'
import { useAnalysis } from '../context/AnalysisContext'
import { generateEvidencePDF } from '../utils/pdfBuilder'

const LEGAL_NOTICE_EN = `⚠️ LEGAL NOTICE: Filing a false or frivolous complaint is a criminal offence punishable under IPC Section 182 and IT Act Section 66. This report has been auto-generated by BobSec AI based on the message you provided. You must review it carefully for accuracy before submitting. BobSec does not submit this report on your behalf. Submission is entirely your responsibility.`

const LEGAL_NOTICE_HI = `⚠️ कानूनी सूचना: झूठी या गलत शिकायत दर्ज करना IPC धारा 182 और IT अधिनियम धारा 66 के तहत दंडनीय अपराध है। यह रिपोर्ट BobSec AI द्वारा आपके दिए गए मैसेज के आधार पर बनाई गई है। जमा करने से पहले इसे ध्यान से पढ़ें। BobSec यह रिपोर्ट आपकी तरफ से जमा नहीं करता।`

function LegalModal({ onConfirm, onCancel, hi }) {
  const [checked, setChecked] = useState(false)
  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 px-4">
      <div className="bg-slate-900 border border-red-700 rounded-2xl p-6 max-w-md w-full">
        <h3 className="text-red-400 font-bold text-base mb-4">
          {hi ? '⚠️ कानूनी सूचना — आगे बढ़ने से पहले पढ़ें' : '⚠️ LEGAL NOTICE — Read Before Proceeding'}
        </h3>
        <div className="bg-red-950 border border-red-800 rounded-lg p-4 mb-4">
          <p className="text-red-200 text-xs leading-relaxed">{LEGAL_NOTICE_EN}</p>
        </div>
        <div className="bg-slate-800 border border-slate-700 rounded-lg p-4 mb-4">
          <p className="text-slate-300 text-xs leading-relaxed">{LEGAL_NOTICE_HI}</p>
        </div>
        <label className="flex items-start gap-3 cursor-pointer mb-5">
          <input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} className="mt-0.5 flex-shrink-0 accent-blue-500" />
          <span className="text-slate-300 text-sm">
            {hi
              ? 'मैंने ऊपर लिखी बात पढ़ और समझ ली है। मैं पुष्टि करता/करती हूँ कि यह report सही है।'
              : 'I have read and understood the above. I confirm this report is accurate.'}
          </span>
        </label>
        <div className="flex gap-3">
          <button onClick={onCancel} className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-sm transition-colors">
            {hi ? 'रद्द करें' : 'Cancel'}
          </button>
          <button
            onClick={onConfirm}
            disabled={!checked}
            className="flex-1 py-3 bg-blue-700 hover:bg-blue-600 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-xl text-sm font-semibold transition-colors"
          >
            {hi ? 'Report बनाएं →' : 'Generate Report →'}
          </button>
        </div>
      </div>
    </div>
  )
}

// Helper to estimate potential loss prevented
function estimateLossPrevented(analysis) {
  const categoryLoss = {
    FINANCIAL_FRAUD: 25000,
    PHISHING: 15000,
    JOB_SCAM: 5000,
    LOTTERY_SCAM: 10000,
    IMPERSONATION: 50000,
    INVESTMENT_SCAM: 100000,
    UNKNOWN: 0
  }
  
  const baseLoss = categoryLoss[analysis.category] || 0
  
  // Adjust based on risk score
  const riskMultiplier = analysis.risk_score / 100
  
  return Math.round(baseLoss * riskMultiplier)
}

export default function Screen4Evidence({ onBack, onReport }) {
  const { analysis, lang, setUserConfirmed, showToast } = useAnalysis()
  const hi = lang === 'hi'
  const [showModal, setShowModal] = useState(false)
  const [copied, setCopied] = useState(false)

  if (!analysis) return null

  function buildCertText() {
    const phones = analysis.entities.phone_numbers?.map(p => `${p.value} (${p.verdict}${p.report_count ? ', ' + p.report_count + ' reports' : ''})`).join(', ') || 'None'
    const urls = analysis.entities.urls?.map(u => `${u.value} (${u.verdict}${u.domain_age_days ? ', ' + u.domain_age_days + ' days old' : ''})`).join(', ') || 'None'
    const upis = analysis.entities.upi_ids?.map(u => `${u.value} (${u.verdict})`).join(', ') || 'None'

    return `BOBSEC EVIDENCE CERTIFICATE
${'─'.repeat(50)}
Analysis ID    : ${analysis.analysis_id}
Timestamp      : ${analysis.timestamp_ist}
Model          : IBM Granite via watsonx.ai
Risk Score     : ${analysis.risk_score} / 100 (${analysis.risk_level})
Confidence     : ${analysis.confidence}%
Category       : ${analysis.category}
Sub-type       : ${analysis.sub_type || 'N/A'}

ENTITIES IDENTIFIED
Phone   : ${phones}
URL     : ${urls}
UPI     : ${upis}
Org     : ${analysis.entities.impersonated_org || 'None'}

RED FLAGS
${analysis.red_flags?.map(f => '· ' + f).join('\n') || 'None'}

VERIFICATION CHAIN
${analysis.trace?.map(t => `Step ${t.step}: ${t.agent} → ${t.result}`).join('\n') || 'N/A'}

${'─'.repeat(50)}
This evidence package was generated by BobSec AI (IBM Bob / watsonx.ai).
It reflects AI analysis only and does not constitute legal or forensic proof.`
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(buildCertText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
    showToast(
      hi ? 'Evidence text कॉपी हो गया। इसे सुरक्षित रखें।' : 'Evidence text copied. Keep it safe.',
      'success'
    )
  }

  function handleDownloadPDF() {
    generateEvidencePDF(analysis)
    showToast(
      hi ? 'Evidence फाइल तैयार है। इसे सुरक्षित रखें — इसमें आपका डेटा है।' : 'Evidence file ready. Keep it safe — it contains your data.',
      'success',
      4000
    )
  }

  function handleConfirm() {
    setShowModal(false)
    setUserConfirmed(true)
    onReport()
  }

  return (
    <div className="min-h-screen px-4 py-8 max-w-xl mx-auto">
      {showModal && <LegalModal onConfirm={handleConfirm} onCancel={() => setShowModal(false)} hi={hi} />}

      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <button onClick={onBack} className="text-slate-400 hover:text-white text-sm transition-colors">← {hi ? 'वापस' : 'Back'}</button>
        <span className="text-slate-600">|</span>
        <span className="text-slate-300 text-sm font-medium">📦 {hi ? 'Evidence Package' : 'Evidence Package'}</span>
      </div>

      {/* Certificate */}
      <div className="bg-slate-950 border border-slate-700 rounded-2xl p-5 mb-6 font-mono text-xs text-slate-300 leading-relaxed">
        <div className="border-b border-slate-700 pb-3 mb-4">
          <p className="text-white font-bold text-sm">BOBSEC EVIDENCE CERTIFICATE</p>
          <p className="text-slate-500 text-xs mt-1">Generated by IBM Bob / watsonx.ai</p>
        </div>

        <div className="grid grid-cols-2 gap-x-4 gap-y-1 mb-4">
          <div><span className="text-slate-500">Analysis ID</span><br/><span className="text-white">{analysis.analysis_id}</span></div>
          <div><span className="text-slate-500">Risk Score</span><br/><span className="text-white">{analysis.risk_score}/100 ({analysis.risk_level})</span></div>
          <div><span className="text-slate-500">Timestamp</span><br/><span className="text-white">{analysis.timestamp_ist}</span></div>
          <div><span className="text-slate-500">Confidence</span><br/><span className="text-white">{analysis.confidence}%</span></div>
          <div><span className="text-slate-500">Category</span><br/><span className="text-white">{analysis.category}</span></div>
          <div><span className="text-slate-500">Model</span><br/><span className="text-white">IBM Granite</span></div>
        </div>

        <div className="border-t border-slate-800 pt-3 mb-3">
          <p className="text-slate-500 mb-2">ENTITIES IDENTIFIED</p>
          {analysis.entities.phone_numbers?.map((p, i) => (
            <p key={i} className="text-slate-300">📞 {p.value} — <span className={p.verdict === 'FLAGGED' ? 'text-red-400' : 'text-emerald-400'}>{p.verdict}</span>{p.report_count ? ` (${p.report_count} rpts)` : ''}</p>
          ))}
          {analysis.entities.urls?.map((u, i) => (
            <p key={i} className="text-slate-300">🔗 {u.value} — <span className={u.verdict === 'MALICIOUS' ? 'text-red-400' : 'text-emerald-400'}>{u.verdict}</span>{u.domain_age_days ? ` (${u.domain_age_days}d old, ${u.feed_hits} feeds)` : ''}</p>
          ))}
          {analysis.entities.upi_ids?.map((u, i) => (
            <p key={i} className="text-slate-300">💳 {u.value} — <span className={u.verdict === 'FLAGGED' ? 'text-red-400' : 'text-emerald-400'}>{u.verdict}</span>{u.report_count ? ` (${u.report_count} rpts)` : ''}</p>
          ))}
          {analysis.entities.impersonated_org && (
            <p className="text-slate-300">🏛 {analysis.entities.impersonated_org} — <span className="text-red-400">IMPERSONATED</span></p>
          )}
        </div>

        <div className="border-t border-slate-800 pt-3 mb-3">
          <p className="text-slate-500 mb-2">RED FLAGS</p>
          {analysis.red_flags?.map((f, i) => (
            <p key={i} className="text-slate-300">· {f}</p>
          ))}
        </div>

        <div className="border-t border-slate-800 pt-3">
          <p className="text-slate-500 mb-2">VERIFICATION CHAIN</p>
          <p className="text-slate-400">
            {analysis.trace?.map(t => t.agent).join(' → ')}
          </p>
        </div>

        <div className="border-t border-slate-800 pt-3 mt-3">
          <p className="text-slate-600 text-xs">This evidence package was generated by BobSec AI (IBM Bob / watsonx.ai). It reflects AI analysis only and does not constitute legal or forensic proof.</p>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mb-4 p-3 bg-amber-950 border border-amber-800 rounded-lg">
        <p className="text-amber-200 text-xs leading-relaxed">
          {hi
            ? '⚠️ इस demo में इस्तेमाल किया गया scam डेटा एक छोटा internal सेट और पैटर्न पर आधारित है, किसी सरकारी/बैंक सिस्टम से direct नहीं।'
            : '⚠️ Scam intelligence in this demo is based on a small internal dataset and patterns, not full government/bank systems.'}
        </p>
      </div>

      {/* Economic impact card */}
      {analysis.risk_level === 'HIGH' && (
        <div className="mb-4 p-4 bg-emerald-950 border border-emerald-800 rounded-xl">
          <div className="flex items-start gap-3">
            <span className="text-2xl flex-shrink-0">💰</span>
            <div className="flex-1">
              <p className="text-emerald-300 text-sm font-semibold mb-1">
                {hi ? 'संभावित नुकसान से बचाया गया' : 'Potential Loss Prevented'}
              </p>
              <p className="text-emerald-200 text-xs mb-2">
                {hi
                  ? `इस scam को पहचानकर, आपने अनुमानित ₹${estimateLossPrevented(analysis).toLocaleString('en-IN')} का नुकसान रोका।`
                  : `By catching this scam, you prevented an estimated loss of ₹${estimateLossPrevented(analysis).toLocaleString('en-IN')}.`}
              </p>
              <p className="text-emerald-400 text-xs italic">
                {hi
                  ? '✨ हर report दूसरों को भी सुरक्षित रखने में मदद करती है।'
                  : '✨ Every report helps keep others safe too.'}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Action buttons */}
      <div className="flex gap-3 mb-4">
        <button onClick={handleCopy} className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-200 rounded-xl text-sm font-medium transition-colors">
          {copied ? '✓ Copied!' : `📋 ${hi ? 'Evidence Copy करें' : 'Copy Evidence'}`}
        </button>
        <button onClick={handleDownloadPDF} className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-200 rounded-xl text-sm font-medium transition-colors">
          ⬇ Download PDF
        </button>
      </div>

      <button
        onClick={() => setShowModal(true)}
        className="w-full py-4 bg-blue-700 hover:bg-blue-600 text-white rounded-xl text-sm font-semibold transition-colors"
      >
        📄 {hi ? 'Police Report बनाएं' : 'Generate Police Report'}
      </button>
      <p className="text-center text-slate-500 text-xs mt-3">
        {hi ? 'Police report के लिए आपकी पुष्टि और समीक्षा ज़रूरी है।' : 'The police report requires your confirmation and review before it is ready to submit.'}
      </p>
    </div>
  )
}

// Made with Bob
