// Police Report Generator - Creates NCRP-formatted reports

const CATEGORY_TO_INCIDENT_TYPE = {
  'FINANCIAL_FRAUD': 'Online Financial Fraud',
  'PHISHING': 'Phishing / Credential Theft',
  'JOB_SCAM': 'Online Job Fraud',
  'LOTTERY_SCAM': 'Lottery / Prize Fraud',
  'IMPERSONATION': 'Impersonation of Government/Bank',
  'INVESTMENT_SCAM': 'Investment / Ponzi Fraud',
  'UNKNOWN': 'Cybercrime (Unclassified)'
};

export function generatePoliceReport(analysisData) {
  const incidentType = CATEGORY_TO_INCIDENT_TYPE[analysisData.category] || 'Cybercrime (Unclassified)';
  
  // Extract entities for report
  const phones = analysisData.entities.phone_numbers?.map(p => p.value).join(', ') || 'unknown sender';
  const urls = analysisData.entities.urls?.map(u => u.value).join(', ') || 'none';
  const upis = analysisData.entities.upi_ids?.map(u => u.value).join(', ') || 'none';
  const impersonatedOrg = analysisData.entities.impersonated_org || 'unknown entity';
  const urgencyPhrase = analysisData.entities.urgency_phrases?.[0] || 'immediate action required';
  
  // Build URL details section
  let urlDetails = '';
  if (analysisData.entities.urls && analysisData.entities.urls.length > 0) {
    const url = analysisData.entities.urls[0];
    urlDetails = `\n\nThe message contained a suspicious link (${url.value}) which BobSec identified as a ${url.verdict.toLowerCase()} domain registered ${url.domain_age_days} days ago and flagged by ${url.feed_hits} threat intelligence sources.`;
  }
  
  // Build phone details section
  let phoneDetails = '';
  if (analysisData.entities.phone_numbers && analysisData.entities.phone_numbers.length > 0) {
    const phone = analysisData.entities.phone_numbers[0];
    phoneDetails = `\n\nThe phone number (${phone.value}) has been reported ${phone.report_count} times for similar ${phone.scam_type?.replace(/_/g, ' ').toLowerCase()} activity.`;
  }
  
  // Build UPI details section
  let upiDetails = '';
  if (analysisData.entities.upi_ids && analysisData.entities.upi_ids.length > 0) {
    const upi = analysisData.entities.upi_ids[0];
    upiDetails = `\n\nThe UPI ID (${upi.value}) has been reported ${upi.report_count} times for fraud.`;
  }
  
  const report = `CYBERCRIME COMPLAINT — NCRP FORMAT
═══════════════════════════════════════════════════════════

SECTION A — INCIDENT DETAILS
Incident Type    : ${incidentType}
Date & Time      : ${analysisData.timestamp_ist}
Platform         : WhatsApp / SMS

SECTION B — COMPLAINT DESCRIPTION
On ${analysisData.timestamp_ist}, I received a message from ${phones} that impersonated ${impersonatedOrg}. The message claimed "${urgencyPhrase}" and directed me to take action that would have compromised my personal and financial information.${urlDetails}${phoneDetails}${upiDetails}

Red flags identified: ${analysisData.red_flags.join(', ')}.

I am filing this complaint to assist in investigation and to warn others.
I request appropriate action against the fraudulent ${phones !== 'unknown sender' ? 'number' : 'sender'}${urls !== 'none' ? '/domain' : ''}.

SECTION C — EVIDENCE SUMMARY
Evidence Type    : AI-Generated Threat Analysis (BobSec / IBM Bob)
Analysis ID      : ${analysisData.analysis_id}
Timestamp        : ${analysisData.timestamp_ist}
Risk Score       : ${analysisData.risk_score} / 100
Confidence Level : ${analysisData.confidence}%
Entities Found   : Phones: ${phones} | URLs: ${urls} | UPI: ${upis}
Intel Feed Hits  : ${analysisData.entities.urls?.[0]?.feed_hits || 0} CTI feed matches
Model Used       : IBM Granite via watsonx.ai

═══════════════════════════════════════════════════════════
This report was auto-generated by BobSec AI. The complainant has reviewed and
confirms its accuracy before submission.

SUBMISSION INSTRUCTIONS:
1. Go to cybercrime.gov.in
2. Click "Report Cyber Crime"
3. Select the incident type matching your complaint
4. Paste this report in the description field
5. Upload your Evidence Package PDF as an attachment

🆘 National Cyber Crime Helpline: 1930 (24/7, free)`;

  return report;
}

export function generateEvidencePackage(analysisData, userMessage) {
  const evidence = `BOBSEC EVIDENCE PACKAGE
═══════════════════════════════════════════════════════════

Analysis ID: ${analysisData.analysis_id}
Generated: ${analysisData.timestamp_ist}

ORIGINAL MESSAGE RECEIVED:
───────────────────────────────────────────────────────────
${userMessage}
───────────────────────────────────────────────────────────

THREAT ANALYSIS SUMMARY:
Risk Level: ${analysisData.risk_level}
Risk Score: ${analysisData.risk_score}/100
Category: ${analysisData.category}
Sub-Type: ${analysisData.sub_type}
Confidence: ${analysisData.confidence}%

RED FLAGS DETECTED:
${analysisData.red_flags.map((flag, i) => `${i + 1}. ${flag}`).join('\n')}

EXTRACTED ENTITIES:

Phone Numbers:
${analysisData.entities.phone_numbers?.map(p => 
  `  • ${p.value} - ${p.verdict} (${p.report_count} reports, ${p.scam_type || 'N/A'})`
).join('\n') || '  None detected'}

URLs/Domains:
${analysisData.entities.urls?.map(u => 
  `  • ${u.value} - ${u.verdict}\n    Age: ${u.domain_age_days} days | Feed Hits: ${u.feed_hits}\n    Reason: ${u.reason}`
).join('\n') || '  None detected'}

UPI IDs:
${analysisData.entities.upi_ids?.map(u => 
  `  • ${u.value} - ${u.verdict} (${u.report_count} reports)`
).join('\n') || '  None detected'}

Impersonated Organization: ${analysisData.entities.impersonated_org || 'None'}

Urgency Phrases:
${analysisData.entities.urgency_phrases?.map(p => `  • "${p}"`).join('\n') || '  None detected'}

EXPLANATION:
${analysisData.explanation_en}

RECOMMENDED ACTION:
${analysisData.user_action}

ORCHESTRATION TRACE:
${analysisData.trace.map((t, i) => 
  `Step ${t.step}: ${t.agent} (${t.model})
  Action: ${t.action}
  Result: ${t.result}
  Time: ${t.time_ms}ms
  Policy: ${t.policy_passed ? 'PASSED' : 'FAILED'}`
).join('\n\n')}

═══════════════════════════════════════════════════════════
This evidence package was generated by BobSec AI using IBM Bob
orchestration and IBM Granite models via watsonx.ai.

For questions or support: cybercrime.gov.in | 1930
═══════════════════════════════════════════════════════════`;

  return evidence;
}

export function getSubmissionInstructions(language = 'en') {
  const instructions = {
    en: [
      "Go to cybercrime.gov.in",
      "Click 'Report Cyber Crime'",
      "Select the incident type matching your complaint",
      "Paste this report in the description field",
      "Upload your Evidence Package PDF as an attachment"
    ],
    hi: [
      "cybercrime.gov.in पर जाएं",
      "'Report Cyber Crime' पर क्लिक करें",
      "अपनी शिकायत से मेल खाने वाला incident type चुनें",
      "यह report description field में paste करें",
      "अपना Evidence Package PDF attachment के रूप में upload करें"
    ]
  };
  
  return instructions[language] || instructions.en;
}

// Made with Bob
